/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConvertersUrlEncoderRouteImport } from './routes/converters/url-encoder'
import { Route as ConvertersTextToHexadecimalRouteImport } from './routes/converters/text-to-hexadecimal'
import { Route as ConvertersTextToBinaryRouteImport } from './routes/converters/text-to-binary'
import { Route as ConvertersTextToBase64RouteImport } from './routes/converters/text-to-base64'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertersUrlEncoderRoute = ConvertersUrlEncoderRouteImport.update({
  id: '/converters/url-encoder',
  path: '/converters/url-encoder',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertersTextToHexadecimalRoute =
  ConvertersTextToHexadecimalRouteImport.update({
    id: '/converters/text-to-hexadecimal',
    path: '/converters/text-to-hexadecimal',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConvertersTextToBinaryRoute = ConvertersTextToBinaryRouteImport.update({
  id: '/converters/text-to-binary',
  path: '/converters/text-to-binary',
  getParentRoute: () => rootRouteImport,
} as any)
const ConvertersTextToBase64Route = ConvertersTextToBase64RouteImport.update({
  id: '/converters/text-to-base64',
  path: '/converters/text-to-base64',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/converters/text-to-base64': typeof ConvertersTextToBase64Route
  '/converters/text-to-binary': typeof ConvertersTextToBinaryRoute
  '/converters/text-to-hexadecimal': typeof ConvertersTextToHexadecimalRoute
  '/converters/url-encoder': typeof ConvertersUrlEncoderRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/converters/text-to-base64': typeof ConvertersTextToBase64Route
  '/converters/text-to-binary': typeof ConvertersTextToBinaryRoute
  '/converters/text-to-hexadecimal': typeof ConvertersTextToHexadecimalRoute
  '/converters/url-encoder': typeof ConvertersUrlEncoderRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/converters/text-to-base64': typeof ConvertersTextToBase64Route
  '/converters/text-to-binary': typeof ConvertersTextToBinaryRoute
  '/converters/text-to-hexadecimal': typeof ConvertersTextToHexadecimalRoute
  '/converters/url-encoder': typeof ConvertersUrlEncoderRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/converters/text-to-base64'
    | '/converters/text-to-binary'
    | '/converters/text-to-hexadecimal'
    | '/converters/url-encoder'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/converters/text-to-base64'
    | '/converters/text-to-binary'
    | '/converters/text-to-hexadecimal'
    | '/converters/url-encoder'
  id:
    | '__root__'
    | '/'
    | '/converters/text-to-base64'
    | '/converters/text-to-binary'
    | '/converters/text-to-hexadecimal'
    | '/converters/url-encoder'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConvertersTextToBase64Route: typeof ConvertersTextToBase64Route
  ConvertersTextToBinaryRoute: typeof ConvertersTextToBinaryRoute
  ConvertersTextToHexadecimalRoute: typeof ConvertersTextToHexadecimalRoute
  ConvertersUrlEncoderRoute: typeof ConvertersUrlEncoderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converters/url-encoder': {
      id: '/converters/url-encoder'
      path: '/converters/url-encoder'
      fullPath: '/converters/url-encoder'
      preLoaderRoute: typeof ConvertersUrlEncoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converters/text-to-hexadecimal': {
      id: '/converters/text-to-hexadecimal'
      path: '/converters/text-to-hexadecimal'
      fullPath: '/converters/text-to-hexadecimal'
      preLoaderRoute: typeof ConvertersTextToHexadecimalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converters/text-to-binary': {
      id: '/converters/text-to-binary'
      path: '/converters/text-to-binary'
      fullPath: '/converters/text-to-binary'
      preLoaderRoute: typeof ConvertersTextToBinaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/converters/text-to-base64': {
      id: '/converters/text-to-base64'
      path: '/converters/text-to-base64'
      fullPath: '/converters/text-to-base64'
      preLoaderRoute: typeof ConvertersTextToBase64RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConvertersTextToBase64Route: ConvertersTextToBase64Route,
  ConvertersTextToBinaryRoute: ConvertersTextToBinaryRoute,
  ConvertersTextToHexadecimalRoute: ConvertersTextToHexadecimalRoute,
  ConvertersUrlEncoderRoute: ConvertersUrlEncoderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
